# SPDX-FileCopyrightText: 2022 Dusan Mijatovic (dv4all)
# SPDX-FileCopyrightText: 2022 Ewan Cahen (Netherlands eScience Center) <e.cahen@esciencecenter.nl>
# SPDX-FileCopyrightText: 2022 Netherlands eScience Center
# SPDX-FileCopyrightText: 2022 dv4all
#
# SPDX-License-Identifier: Apache-2.0

name: all tests

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - "database/**"
      - "backend-postgrest/**"
      - "scrapers/**"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "install node v16 and cash yarn"
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - name: "install dependencies"
        working-directory: frontend
        run: yarn install --frozen-lockfile
      - name: "run unit test"
        working-directory: frontend
        run: yarn test:coverage

  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "newman tests with docker-compose"
        working-directory: backend-postgrest/tests
        run: |
          docker-compose up \
            --abort-on-container-exit \
            --exit-code-from postgrest-tests

  scrapers-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Maven JUnit tests"
        working-directory: scrapers
        run: |
          JAVA_HOME=$JAVA_HOME_17_X64 mvn test
